[package]
name = "magnidraw"
version = "0.1.0"
edition = "2024"

[dependencies]
keydraw = "0.1.0"
bytemuck = "1.25.0"
wgpu = "29.0.3"
glyphon = { git = "https://github.com/carsonetb/glyphon", branch = "main" }
image = "0.25.10"
winit = "0.30.13"
winit_input_helper = "0.17.0"
gilrs = "0.11.2"
window_clipboard = "0.5.1"
dyn-clone = "1.0.20"
resvg = "0.47.0"
usvg = "0.47.0"
tiny-skia = "0.12.0"
rapier2d = { version = "0.33", optional = true }

[dev-dependencies]
rand = "0.10.1"

[features]
ui = []
physics = ["dep:rapier2d"]
